import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { GoogleOAuthProvider } from "@react-oauth/google";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900", "300", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased max-w-[430px] mx-auto min-h-[932px] bg-mythemes-bgWhite;
        ]`}
      >
        <GoogleOAuthProvider clientId={`${process.env.CLIENT_ID}`}>
          {children}
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
